# name: Pipeline Workflow

# on:
#   push:
#     branches: [ $default-branch ]
#   pull_request:
#     branches: [ $default-branch ]

# jobs:
#   call-workflow-branch-ref:
#     uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@$default-branch
name: Pipeline Workflow

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
  call-workflow-branch-ref:
    uses: tshadz-fiap-postech-soat3/ci-pipeline/.github/workflows/ci-pipeline.yml@$default-branch
    # steps:
    #   - uses: actions/checkout@v4

    #   - name: Run a one-line script
    #     run: echo Hello from Octo Organization
